using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace MoonBit2CSharp.Backend;

internal static class CSharpRuntimeSource
{
    private static readonly Lazy<RuntimeSourceDocument> RuntimeSource = new(LoadRuntimeSource);

    public static string SourceHash => RuntimeSource.Value.Hash;

    public static string Emit(string runtimeNamespace, string newLine, bool finalNewLine)
    {
        return Emit(runtimeNamespace, newLine, finalNewLine, null);
    }

    public static string Emit(
        string runtimeNamespace,
        string newLine,
        bool finalNewLine,
        IReadOnlySet<string>? excludedTypeNames
    )
    {
        var source = RuntimeSource.Value.Source;
        source = Regex.Replace(
            source,
            @"namespace\s+MoonBit2CSharp\.Runtime\s*;",
            "namespace " + runtimeNamespace + ";",
            RegexOptions.CultureInvariant
        );

        if (excludedTypeNames is { Count: > 0 })
        {
            var members = Members(runtimeNamespace, excludedTypeNames);
            var unit = CompilationUnit()
                .WithUsings(SingletonList(UsingDirective(ParseName("System"))))
                .WithMembers(
                    SingletonList<MemberDeclarationSyntax>(
                        FileScopedNamespaceDeclaration(ParseName(runtimeNamespace))
                            .AddMembers(members.ToArray())
                    )
                )
                .NormalizeWhitespace("    ", newLine);
            source =
                "// <auto-generated/>"
                + newLine
                + "#nullable enable"
                + newLine
                + "#pragma warning disable CS8509, CS8846"
                + newLine
                + newLine
                + unit.ToFullString();
        }

        if (newLine != "\n")
            source = source
                .Replace("\r\n", "\n", StringComparison.Ordinal)
                .Replace("\n", newLine, StringComparison.Ordinal);

        return finalNewLine || source.EndsWith(newLine, StringComparison.Ordinal)
            ? source
            : source + newLine;
    }

    public static IReadOnlyList<MemberDeclarationSyntax> Members(
        string runtimeNamespace,
        IReadOnlySet<string>? excludedTypeNames = null
    )
    {
        var source = Emit(runtimeNamespace, "\n", true);
        var unit = CSharpSyntaxTree.ParseText(source).GetCompilationUnitRoot();
        return unit
            .Members.OfType<BaseNamespaceDeclarationSyntax>()
            .Single(namespaceDecl =>
                string.Equals(
                    namespaceDecl.Name.ToString(),
                    runtimeNamespace,
                    StringComparison.Ordinal
                )
            )
            .Members.Where(member => !IsExcludedType(member, excludedTypeNames))
            .ToArray();
    }

    private static bool IsExcludedType(
        MemberDeclarationSyntax member,
        IReadOnlySet<string>? excludedTypeNames
    )
    {
        return excludedTypeNames is not null
            && member is BaseTypeDeclarationSyntax typeDecl
            && excludedTypeNames.Contains(typeDecl.Identifier.ValueText);
    }

    private static RuntimeSourceDocument LoadRuntimeSource()
    {
        var path = FindRuntimeSourcePath();
        var source = File.ReadAllText(path);
        var hash = Convert
            .ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(source)))
            .ToLowerInvariant();
        return new(source, hash);
    }

    private static string FindRuntimeSourcePath()
    {
        var configured = Environment.GetEnvironmentVariable("MOONBIT2CSHARP_RUNTIME_SOURCE");
        if (!string.IsNullOrWhiteSpace(configured) && File.Exists(configured))
            return Path.GetFullPath(configured);

        foreach (var start in CandidateStarts())
        {
            var current = new DirectoryInfo(start);
            while (current is not null)
            {
                var candidate = Path.Combine(
                    current.FullName,
                    "csharp",
                    "MoonBitRuntime",
                    "Runtime.cs"
                );
                if (File.Exists(candidate))
                    return candidate;

                current = current.Parent;
            }
        }

        throw new InvalidOperationException(
            "MoonBit runtime source not found. Set MOONBIT2CSHARP_RUNTIME_SOURCE to csharp/MoonBitRuntime/Runtime.cs."
        );
    }

    private static IEnumerable<string> CandidateStarts()
    {
        yield return AppContext.BaseDirectory;
        yield return Environment.CurrentDirectory;
    }

    private sealed record RuntimeSourceDocument(string Source, string Hash);
}
