///|
pub impl Add for UInt64 with add(self, other) = "%u64.add"

///|
pub impl Sub for UInt64 with sub(self, other) = "%u64.sub"

///|
pub impl Mul for UInt64 with mul(self, other) = "%u64.mul"

///|
pub impl Div for UInt64 with div(self, other) = "%u64.div"

///|
pub impl Mod for UInt64 with mod(self, other) = "%u64.mod"

///|
pub impl BitAnd for UInt64 with land(self, other) = "%u64.bitand"

///|
pub impl BitOr for UInt64 with lor(self, other) = "%u64.bitor"

///|
pub impl BitXOr for UInt64 with lxor(self, other) = "%u64.bitxor"

///|
pub impl Shl for UInt64 with shl(self, other) = "%u64.shl"

///|
pub impl Shr for UInt64 with shr(self, other) = "%u64.shr"

///|
pub impl Eq for UInt64 with equal(self, other) = "%u64.eq"

///|
pub impl Eq for UInt64 with not_equal(self, other) = "%u64.ne"

///|
pub impl Compare for UInt64 with compare(self, other) = "%u64.compare"

///|
pub impl Compare for UInt64 with op_lt(self, other) = "%u64.lt"

///|
pub impl Compare for UInt64 with op_le(self, other) = "%u64.le"

///|
pub impl Compare for UInt64 with op_gt(self, other) = "%u64.gt"

///|
pub impl Compare for UInt64 with op_ge(self, other) = "%u64.ge"
