// <auto-generated/>
#nullable enable
#pragma warning disable CS8509, CS8846

using System;
using System.Collections.Generic;

namespace MoonBit.Runtime;
public readonly record struct MoonBitUnit
{
    public static readonly MoonBitUnit Value = new();
}

public sealed class MoonBitPanic : Exception
{
    public MoonBitPanic(string message = "panic") : base(message)
    {
    }
}

public readonly record struct MoonBitSourceLoc(string Repr)
{
    public override string ToString() => Repr;
}

public readonly record struct MoonBitArgsLoc(MoonBitOption<MoonBitSourceLoc>[] Items);

public readonly struct MoonBitOption<T>
{
    private readonly T? value;
    private MoonBitOption(T? value, bool isSome)
    {
        this.value = value;
        IsSome = isSome;
    }

    public bool IsSome { get; }
    public bool IsNone => !IsSome;
    public T Value => IsSome ? value! : throw new InvalidOperationException("called Option::unwrap() on None");

    public T Unwrap() => Value;
    public T UnwrapOr(T fallback) => IsSome ? value! : fallback;
    public bool IsEmpty() => IsNone;
    public static MoonBitOption<T> Some(T value) => new(value, true);
    public static MoonBitOption<T> None() => new(default, false);
    public override string ToString() => IsSome ? "Some(" + value!.ToString() + ")" : "None";
}

public class MoonBitError
{
    public object Self { get; }
    public IShowImpl? Impl { get; }
    public string DisplayName { get; }
    public MoonBitError(
        object self,
        IShowImpl? showImpl,
        string displayName
    )
    {
        this.Self = self;
        this.Impl = showImpl;
        this.DisplayName = displayName;
    }

    public static MoonBitError FromObject<T, TImpl>(T value)
        where TImpl : IShowImpl<T, TImpl> =>
        new MoonBitError(value!, ShowImplObject<T, TImpl>.Instance, "");
    public static MoonBitError FromObject(object value, string displayName) =>
        new MoonBitError(value!, null, displayName);
    public static MoonBitError FromObject(object value, string displayName, IShowImpl impl) =>
        new MoonBitError(value!, impl, displayName);

    public override string ToString() =>
        Impl is not null ? Impl.ToString(Self) : DisplayName;

    public MoonBitUnit Output(Logger logger)
    {
        logger.WriteString(ToString());
        return MoonBitUnit.Value;
    }
}

public readonly record struct MoonBitResult<TOk, TError>(bool IsOk, TOk? Value, TError? Error)
{
    public static MoonBitResult<TOk, TError> Ok(TOk value) => new(true, value, default);
    public static MoonBitResult<TOk, TError> Err(TError error) => new(false, default, error);
}

public static class MoonBitCoreMath
{
    public static float DefaultFloat() => 0.0f;
    public static double ExpM1(double x) => Math.Exp(x) - 1.0;
    public static float ExpM1(float x) => MathF.Exp(x) - 1.0f;
    public static double Log1P(double x) => Math.Log(1.0 + x);
    public static float Log1P(float x) => MathF.Log(1.0f + x);
}

public readonly record struct Logger(object Self, ILoggerImpl Impl)
{
    public MoonBitUnit WriteString(string value) => Impl.WriteString(Self, value);
    public MoonBitUnit WriteView(MoonBitStringView value) => Impl.WriteView(Self, value);
    public MoonBitUnit WriteChar(int value) => Impl.WriteChar(Self, value);
}

public interface ILoggerImpl
{
    MoonBitUnit WriteString(object self, string value);
    MoonBitUnit WriteView(object self, MoonBitStringView value);
    MoonBitUnit WriteChar(object self, int value);
}

public sealed class MoonBitStringBuilderAsLogger : ILoggerImpl
{
    public static readonly MoonBitStringBuilderAsLogger Instance = new();
    private MoonBitStringBuilderAsLogger()
    {
    }

    public MoonBitUnit WriteString(object self, string value) =>
        ((MoonBitStringBuilder)self).WriteString(value);

    public MoonBitUnit WriteView(object self, MoonBitStringView value) =>
        ((MoonBitStringBuilder)self).WriteString(value.ToString());

    public MoonBitUnit WriteChar(object self, int value) =>
        ((MoonBitStringBuilder)self).WriteChar(value);
}

public readonly record struct ShowObject(object Self, IShowImpl Impl);

public interface IShowImpl
{
    string ToString(object self);
    MoonBitUnit Output(object self, Logger logger);
}

public interface IShowImpl<T, TImpl>
    where TImpl : IShowImpl<T, TImpl>
{
    static virtual MoonBitUnit Output(T value, Logger logger)
    {
        logger.WriteString(TImpl.ToString(value));
        return MoonBitUnit.Value;
    }

    static virtual string ToString(T value) =>
        MoonBitShow.ToMoonBitStringViaOutput<T, TImpl>(value);
}

public static class Show
{
    public static MoonBitUnit Output<T, TImpl>(T value, Logger logger)
        where TImpl : IShowImpl<T, TImpl> => TImpl.Output(value, logger);

    public static string ToString<T, TImpl>(T value)
        where TImpl : IShowImpl<T, TImpl> => TImpl.ToString(value);
}

public sealed class ShowImplObject<T, TImpl> : IShowImpl where TImpl : IShowImpl<T, TImpl>
{
    public static readonly ShowImplObject<T, TImpl> Instance = new();
    private ShowImplObject() { }
    public MoonBitUnit Output(object self, Logger logger)
    {
        return TImpl.Output((T)self, logger);
    }
    public string ToString(object self) => TImpl.ToString((T)self);
}

public static class MoonBitShow
{
    public static string QuoteString(string value) => "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

    public static string ToMoonBitStringViaOutput<T, TShowImpl>(T value)
        where TShowImpl : IShowImpl<T, TShowImpl>
    {
        var logger = new MoonBitStringBuilder();
        TShowImpl.Output(value, new Logger(logger, MoonBitStringBuilderAsLogger.Instance));
        return logger.ToString();
    }

    private static MoonBitUnit WriteSpan<T, TShowImpl>(Logger logger, ReadOnlySpan<T> values, string prefix = "[", string suffix = "]", string sep = ", ", bool trailing = false)
        where TShowImpl : IShowImpl<T, TShowImpl>
    {
        logger.WriteString(prefix);
        for (var i = 0; i < values.Length; i++)
        {
            if (i > 0)
            {
                logger.WriteString(sep);
            }

            TShowImpl.Output(values[i], logger);
            if (trailing)
            {
                logger.WriteString(sep);
            }
        }

        logger.WriteString(suffix);
        return MoonBitUnit.Value;
    }

    public readonly struct Int16ShowImpl : IShowImpl<short, Int16ShowImpl>
    {
        public static string ToString(short value) => value.ToString(System.Globalization.CultureInfo.InvariantCulture);
    }

    public readonly struct IntShowImpl : IShowImpl<int, IntShowImpl>
    {
        public static string ToString(int value) => value.ToString(System.Globalization.CultureInfo.InvariantCulture);
    }

    public readonly struct Int64ShowImpl : IShowImpl<long, Int64ShowImpl>
    {
        public static string ToString(long value) => value.ToString(System.Globalization.CultureInfo.InvariantCulture);
    }

    public readonly struct ByteShowImpl : IShowImpl<byte, ByteShowImpl>
    {
        public static string ToString(byte value) => ShowByte(value);
    }

    public readonly struct UIntShowImpl : IShowImpl<uint, UIntShowImpl>
    {
        public static string ToString(uint value) => value.ToString(System.Globalization.CultureInfo.InvariantCulture);
    }

    public readonly struct UInt16ShowImpl : IShowImpl<ushort, UInt16ShowImpl>
    {
        public static string ToString(ushort value) => value.ToString(System.Globalization.CultureInfo.InvariantCulture);
    }

    public readonly struct UInt64ShowImpl : IShowImpl<ulong, UInt64ShowImpl>
    {
        public static string ToString(ulong value) => value.ToString(System.Globalization.CultureInfo.InvariantCulture);
    }

    public readonly struct FloatShowImpl : IShowImpl<float, FloatShowImpl>
    {
        public static string ToString(float value) => value.ToString(System.Globalization.CultureInfo.InvariantCulture);
    }

    public readonly struct DoubleShowImpl : IShowImpl<double, DoubleShowImpl>
    {
        public static string ToString(double value) => value.ToString(System.Globalization.CultureInfo.InvariantCulture);
    }

    public readonly struct BoolShowImpl : IShowImpl<bool, BoolShowImpl>
    {
        public static string ToString(bool value) => value ? "true" : "false";
    }

    public readonly struct StringShowImpl : IShowImpl<string, StringShowImpl>
    {
        public static MoonBitUnit Output(string value, Logger logger) => logger.WriteString(QuoteString(value));
        public static string ToString(string value) => value;

    }

    public readonly struct CharShowImpl : IShowImpl<int, CharShowImpl>
    {
        public static string ToString(int value) => char.ConvertFromUtf32(value);
    }

    public readonly struct ErrorShowImpl : IShowImpl<MoonBitError, ErrorShowImpl>
    {
        public static MoonBitUnit Output(MoonBitError value, Logger logger)
        {
            return value.Output(logger);
        }

        public static string ToString(MoonBitError value) => value.ToString();
    }

    private static string ShowByte(byte value)
    {
        const string digits = "0123456789ABCDEF";
        return "b'\\x" + digits[value >> 4] + digits[value & 0xF] + "'";
    }

    public readonly struct ShowObjectShowImpl : IShowImpl<ShowObject, ShowObjectShowImpl>
    {
        public static string ToString(ShowObject value) => value.Impl.ToString(value.Self);
        public static MoonBitUnit Output(ShowObject value, Logger logger) => value.Impl.Output(value.Self, logger);
    }

    public readonly struct StringViewShowImpl : IShowImpl<MoonBitStringView, StringViewShowImpl>
    {
        public static MoonBitUnit Output(MoonBitStringView value, Logger logger) => logger.WriteString(QuoteString(value.ToString()));
        public static string ToString(MoonBitStringView value) => value.ToString();
    }

    public sealed class MoonBitOptionShowImpl<T, TShowImpl> : IShowImpl<MoonBitOption<T>, MoonBitOptionShowImpl<T, TShowImpl>>
        where TShowImpl : IShowImpl<T, TShowImpl>
    {
        public static MoonBitUnit Output(MoonBitOption<T> value, Logger logger)
        {
            if (value.IsNone)
            {
                logger.WriteString("None");
                return MoonBitUnit.Value;
            }

            logger.WriteString("Some(");
            TShowImpl.Output(value.Value, logger);
            logger.WriteString(")");
            return MoonBitUnit.Value;
        }

    }

    public sealed class MoonBitResultShowImpl<TOk, TOkShowImpl, TError, TErrorShowImpl> : IShowImpl<MoonBitResult<TOk, TError>, MoonBitResultShowImpl<TOk, TOkShowImpl, TError, TErrorShowImpl>>
        where TOkShowImpl : IShowImpl<TOk, TOkShowImpl>
        where TErrorShowImpl : IShowImpl<TError, TErrorShowImpl>
    {
        public static MoonBitUnit Output(MoonBitResult<TOk, TError> value, Logger logger)
        {
            if (value.IsOk)
            {
                logger.WriteString("Ok(");
                TOkShowImpl.Output(value.Value!, logger);
                logger.WriteString(")");
                return MoonBitUnit.Value;
            }

            logger.WriteString("Err(");
            TErrorShowImpl.Output(value.Error!, logger);
            logger.WriteString(")");
            return MoonBitUnit.Value;
        }

    }

    public sealed class MoonBitArrayShowImpl<T, TShowImpl> : IShowImpl<MoonBitArray<T>, MoonBitArrayShowImpl<T, TShowImpl>>
        where TShowImpl : IShowImpl<T, TShowImpl>
    {
        public static MoonBitUnit Output(MoonBitArray<T> value, Logger logger) =>
            WriteSpan<T, TShowImpl>(logger, value.AsSpan());

    }

    public sealed class FixedArrayShowImpl<T, TShowImpl> : IShowImpl<T[], FixedArrayShowImpl<T, TShowImpl>>
        where TShowImpl : IShowImpl<T, TShowImpl>
    {
        public static MoonBitUnit Output(T[] value, Logger logger) =>
            WriteSpan<T, TShowImpl>(logger, value.AsSpan());

    }

    public sealed class MoonBitArrayViewShowImpl<T, TShowImpl> : IShowImpl<MoonBitArrayView<T>, MoonBitArrayViewShowImpl<T, TShowImpl>>
        where TShowImpl : IShowImpl<T, TShowImpl>
    {
        public static MoonBitUnit Output(MoonBitArrayView<T> value, Logger logger) =>
            WriteSpan<T, TShowImpl>(logger, value.AsSpan());

    }

    public sealed class MoonBitMutArrayViewShowImpl<T, TShowImpl> : IShowImpl<MoonBitMutArrayView<T>, MoonBitMutArrayViewShowImpl<T, TShowImpl>>
        where TShowImpl : IShowImpl<T, TShowImpl>
    {
        public static MoonBitUnit Output(MoonBitMutArrayView<T> value, Logger logger) =>
            WriteSpan<T, TShowImpl>(logger, value.AsSpan());

    }

}

public static class MoonBitConsole
{
    public static MoonBitUnit println<T, TShow>(T value) where TShow : IShowImpl<T, TShow>
    {
        Console.WriteLine(TShow.ToString(value));
        return MoonBitUnit.Value;
    }

}

public static partial class MoonBitIntrinsics
{
    public static MoonBitIter<T> ArrayIter<T>(MoonBitArray<T> self)
    {
        var i = 0;
        return new MoonBitIter<T>(() =>
        {
            if (i >= self.Length)
            {
                return MoonBitOption<T>.None();
            }

            return MoonBitOption<T>.Some(self.Buffer[i++]);
        });
    }

    public static T ArrayRemove<T>(MoonBitArray<T> self, int index)
    {
        if ((uint)index >= (uint)self.Length)
        {
            throw new MoonBitPanic("panic");
        }

        var value = self.Buffer[index];
        Array.Copy(self.Buffer, index + 1, self.Buffer, index, self.Length - index - 1);
        self.Length--;
        self.Buffer[self.Length] = default!;
        return value;
    }

    public static MoonBitArray<T> ArrayMake<T>(int length, T value)
    {
        var result = new MoonBitArray<T>(length);
        for (var i = 0; i < length; i++)
        {
            MoonBitArray.Push(result, value);
        }

        return result;
    }

    public static MoonBitOption<T> ArrayLast<T>(MoonBitArray<T> self)
    {
        return self.Length == 0
            ? MoonBitOption<T>.None()
            : MoonBitOption<T>.Some(self.Buffer[self.Length - 1]);
    }

    public static MoonBitArray<T> ArrayFilter<T>(MoonBitArray<T> self, Func<T, bool> predicate)
    {
        var result = new MoonBitArray<T>();
        for (var i = 0; i < self.Length; i++)
        {
            var item = self.Buffer[i];
            if (predicate(item))
            {
                MoonBitArray.Push(result, item);
            }
        }

        return result;
    }

    public static MoonBitUnit ArraySortBy<T>(MoonBitArray<T> self, Func<T, T, int> compare)
    {
        Array.Sort(self.Buffer, 0, self.Length, Comparer<T>.Create((left, right) => compare(left, right)));
        return MoonBitUnit.Value;
    }

    public static MoonBitUnit PrintlnString(string value)
    {
        Console.WriteLine(value);
        return MoonBitUnit.Value;
    }

    public static MoonBitOption<int> StringViewFind(MoonBitStringView self, MoonBitStringView needle)
    {
        var index = self.AsSpan().IndexOf(needle.AsSpan(), StringComparison.Ordinal);
        return index < 0 ? MoonBitOption<int>.None() : MoonBitOption<int>.Some(index);
    }

    public static MoonBitStringView StringViewView(MoonBitStringView self, int startOffset, MoonBitOption<int> endOffset)
    {
        return self.Sub(startOffset, endOffset.IsSome ? endOffset.Value : self.Length);
    }

    public static MoonBitOption<int> StringGetChar(string self, int index)
    {
        if ((uint)index >= (uint)self.Length)
        {
            return MoonBitOption<int>.None();
        }

        var current = self[index];
        if (char.IsHighSurrogate(current))
        {
            if (index + 1 >= self.Length || !char.IsLowSurrogate(self[index + 1]))
            {
                return MoonBitOption<int>.None();
            }

            return MoonBitOption<int>.Some(char.ConvertToUtf32(current, self[index + 1]));
        }

        return char.IsLowSurrogate(current)
            ? MoonBitOption<int>.None()
            : MoonBitOption<int>.Some(current);
    }

    public static MoonBitOption<int> StringViewGetChar(MoonBitStringView self, int index)
    {
        if ((uint)index >= (uint)self.Length)
        {
            return MoonBitOption<int>.None();
        }

        return StringGetChar(self.Data, self.Start + index);
    }

    public static MoonBitArray<int> StringToArray(MoonBitStringView self)
    {
        var values = new List<int>();
        var index = self.Start;
        while (index < self.End)
        {
            var current = self.Data[index];
            if (char.IsHighSurrogate(current) && index + 1 < self.End && char.IsLowSurrogate(self.Data[index + 1]))
            {
                values.Add(char.ConvertToUtf32(current, self.Data[index + 1]));
                index += 2;
            }
            else
            {
                values.Add(current);
                index++;
            }
        }

        return new MoonBitArray<int>(values.ToArray());
    }

    public static bool StringContainsChar(MoonBitStringView self, int value)
    {
        var index = self.Start;
        while (index < self.End)
        {
            var current = self.Data[index];
            if (char.IsHighSurrogate(current) && index + 1 < self.End && char.IsLowSurrogate(self.Data[index + 1]))
            {
                if (char.ConvertToUtf32(current, self.Data[index + 1]) == value)
                {
                    return true;
                }

                index += 2;
            }
            else
            {
                if (current == value)
                {
                    return true;
                }

                index++;
            }
        }

        return false;
    }

    public static int StringCharLength(MoonBitStringView self)
    {
        var count = 0;
        var index = self.Start;
        while (index < self.End)
        {
            var current = self.Data[index];
            index += char.IsHighSurrogate(current) && index + 1 < self.End && char.IsLowSurrogate(self.Data[index + 1]) ? 2 : 1;
            count++;
        }

        return count;
    }

    public static string StringMake(int length, int value)
    {
        var text = char.ConvertFromUtf32(value);
        return string.Create(text.Length * length, text, static (span, item) =>
        {
            for (var i = 0; i < span.Length; i += item.Length)
            {
                item.AsSpan().CopyTo(span[i..]);
            }
        });
    }

    public static MoonBitStringView StringViewTrim(MoonBitStringView self, MoonBitStringView chars)
    {
        return StringViewTrimEnd(StringViewTrimStart(self, chars), chars);
    }

    public static MoonBitStringView StringViewTrimStart(MoonBitStringView self, MoonBitStringView chars)
    {
        var start = self.Start;
        while (start < self.End && chars.AsSpan().IndexOf(self.Data[start]) >= 0)
        {
            start++;
        }

        return new MoonBitStringView(self.Data, start, self.End);
    }

    public static MoonBitStringView StringViewTrimEnd(MoonBitStringView self, MoonBitStringView chars)
    {
        var end = self.End;
        while (end > self.Start && chars.AsSpan().IndexOf(self.Data[end - 1]) >= 0)
        {
            end--;
        }

        return new MoonBitStringView(self.Data, self.Start, end);
    }
}

public static class MoonBitCompare
{
    public static int Compare<T>(T left, T right)
    {
        if (left is string leftString && right is string rightString)
        {
            return string.Compare(leftString, rightString, StringComparison.Ordinal);
        }

        return Comparer<T>.Default.Compare(left, right);
    }
}

public static class MoonBitOptionEq
{
    public static bool Equal<T, TEqImpl>(MoonBitOption<T> self, MoonBitOption<T> other)
        where TEqImpl : IEqImpl<T, TEqImpl>
    {
        if (self.IsNone || other.IsNone)
        {
            return self.IsNone && other.IsNone;
        }

        return Eq.Equal<T, TEqImpl>(self.Value, other.Value);
    }
}

public readonly struct MoonBitOptionEqImpl<T, TEqImpl> : IEqImpl<MoonBitOption<T>, MoonBitOptionEqImpl<T, TEqImpl>>
    where TEqImpl : IEqImpl<T, TEqImpl>
{
    public static bool Equal(MoonBitOption<T> self, MoonBitOption<T> other) =>
        MoonBitOptionEq.Equal<T, TEqImpl>(self, other);
}

public interface IEqImpl
{
    bool Equal(object left, object right);
    bool NotEqual(object left, object right) => !Equal(left, right);
}

public interface IEqImpl<T, TImpl>
    where TImpl : IEqImpl<T, TImpl>
{
    static abstract bool Equal(T left, T right);
    static virtual bool NotEqual(T left, T right) => !TImpl.Equal(left, right);
}

public static class Eq
{
    public static bool Equal<T, TImpl>(T left, T right)
        where TImpl : IEqImpl<T, TImpl> => TImpl.Equal(left, right);

    public static bool NotEqual<T, TImpl>(T left, T right)
        where TImpl : IEqImpl<T, TImpl> => TImpl.NotEqual(left, right);
}

public sealed class EqImplObject<T, TImpl> : IEqImpl where TImpl : IEqImpl<T, TImpl>
{
    public static readonly EqImplObject<T, TImpl> Instance = new();
    private EqImplObject() { }
    public bool Equal(object left, object right) => TImpl.Equal((T)left, (T)right);
    public bool NotEqual(object left, object right) => TImpl.NotEqual((T)left, (T)right);
}

public static class MoonBitEq
{
    public readonly struct IntEqImpl : IEqImpl<int, IntEqImpl>
    {
        public static bool Equal(int left, int right) => left == right;
    }

    public readonly struct BoolEqImpl : IEqImpl<bool, BoolEqImpl>
    {
        public static bool Equal(bool left, bool right) => left == right;
    }

    public readonly struct StringEqImpl : IEqImpl<string, StringEqImpl>
    {
        public static bool Equal(string left, string right) => string.Equals(left, right, StringComparison.Ordinal);
    }

    public readonly struct DoubleEqImpl : IEqImpl<double, DoubleEqImpl>
    {
        public static bool Equal(double left, double right) => left == right;
    }

    public readonly struct FloatEqImpl : IEqImpl<float, FloatEqImpl>
    {
        public static bool Equal(float left, float right) => left == right;
    }

    public readonly struct UInt16EqImpl : IEqImpl<ushort, UInt16EqImpl>
    {
        public static bool Equal(ushort left, ushort right) => left == right;
    }

    public readonly struct CharEqImpl : IEqImpl<int, CharEqImpl>
    {
        public static bool Equal(int left, int right) => left == right;
    }

    public readonly struct DefaultEqImpl<T> : IEqImpl<T, DefaultEqImpl<T>>
    {
        public static bool Equal(T left, T right) =>
            System.Collections.Generic.EqualityComparer<T>.Default.Equals(left, right);
    }
}

public interface IAddImpl<T>
{
    static abstract T Add(T self, T arg0);
}

public interface ISubImpl<T>
{
    static abstract T Sub(T self, T arg0);
}

public interface IMulImpl<T>
{
    static abstract T Mul(T self, T arg0);
}

public interface IDivImpl<T>
{
    static abstract T Div(T self, T arg0);
}

public interface IModImpl<T>
{
    static abstract T Mod(T self, T arg0);
}

public interface INegImpl<T>
{
    static abstract T Neg(T self);
}

public interface ICompareImpl<T, TImpl>
    where TImpl : ICompareImpl<T, TImpl>
{
    static abstract int Compare(T self, T arg0);
    static virtual bool OpLt(T self, T arg0) => TImpl.Compare(self, arg0) < 0;
    static virtual bool OpGt(T self, T arg0) => TImpl.Compare(self, arg0) > 0;
    static virtual bool OpLe(T self, T arg0) => TImpl.Compare(self, arg0) <= 0;
    static virtual bool OpGe(T self, T arg0) => TImpl.Compare(self, arg0) >= 0;
}

public static class CompareTrait
{
    public static int Compare<T, TImpl>(T self, T arg0)
        where TImpl : ICompareImpl<T, TImpl> => TImpl.Compare(self, arg0);
    public static bool OpLt<T, TImpl>(T self, T arg0)
        where TImpl : ICompareImpl<T, TImpl> => TImpl.OpLt(self, arg0);
    public static bool OpGt<T, TImpl>(T self, T arg0)
        where TImpl : ICompareImpl<T, TImpl> => TImpl.OpGt(self, arg0);
    public static bool OpLe<T, TImpl>(T self, T arg0)
        where TImpl : ICompareImpl<T, TImpl> => TImpl.OpLe(self, arg0);
    public static bool OpGe<T, TImpl>(T self, T arg0)
        where TImpl : ICompareImpl<T, TImpl> => TImpl.OpGe(self, arg0);
}

public static class MoonBitOperators
{
    public readonly struct IntAddImpl : IAddImpl<int>
    {
        public static int Add(int self, int arg0) => self + arg0;
    }

    public readonly struct IntSubImpl : ISubImpl<int>
    {
        public static int Sub(int self, int arg0) => self - arg0;
    }

    public readonly struct IntMulImpl : IMulImpl<int>
    {
        public static int Mul(int self, int arg0) => self * arg0;
    }

    public readonly struct IntDivImpl : IDivImpl<int>
    {
        public static int Div(int self, int arg0) => self / arg0;
    }

    public readonly struct IntModImpl : IModImpl<int>
    {
        public static int Mod(int self, int arg0) => self % arg0;
    }

    public readonly struct IntNegImpl : INegImpl<int>
    {
        public static int Neg(int self) => -self;
    }
}

public sealed class MoonBitIter<T>
{
    private readonly Func<MoonBitOption<T>> next;

    public MoonBitIter(Func<MoonBitOption<T>> next)
    {
        this.next = next;
    }

    public MoonBitOption<T> Next() => next();
}

public static partial class MoonBitIntrinsics
{
    public static bool BoolNot(bool value) => !value;
    public static double F64Add(double left, double right) => left + right;
    public static int F64Compare(double left, double right) => left.CompareTo(right);
    public static double F64Div(double left, double right) => left / right;
    public static bool F64Eq(double left, double right) => left == right;
    public static bool F64Ge(double left, double right) => left >= right;
    public static bool F64Gt(double left, double right) => left > right;
    public static bool F64Le(double left, double right) => left <= right;
    public static bool F64Lt(double left, double right) => left < right;
    public static double F64Mul(double left, double right) => left * right;
    public static bool F64Ne(double left, double right) => left != right;
    public static double F64Neg(double value) => -value;
    public static double F64Sub(double left, double right) => left - right;
    public static int I32Add(int left, int right) => left + right;
    public static int I32Compare(int left, int right) => left.CompareTo(right);
    public static int I32Div(int left, int right) => left / right;
    public static bool I32Eq(int left, int right) => left == right;
    public static bool I32Ge(int left, int right) => left >= right;
    public static bool I32Gt(int left, int right) => left > right;
    public static int I32Land(int left, int right) => left & right;
    public static bool I32Le(int left, int right) => left <= right;
    public static int I32Lnot(int value) => ~value;
    public static int I32Lor(int left, int right) => left | right;
    public static bool I32Lt(int left, int right) => left < right;
    public static int I32Lxor(int left, int right) => left ^ right;
    public static int I32Mod(int left, int right) => left % right;
    public static int I32Mul(int left, int right) => left * right;
    public static bool I32Ne(int left, int right) => left != right;
    public static int I32Neg(int value) => -value;
    public static int I32Shl(int left, int right) => left << right;
    public static int I32Shr(int left, int right) => left >> right;
    public static int I32Sub(int left, int right) => left - right;
    public static uint U32Add(uint left, uint right) => left + right;
    public static uint U32BitAnd(uint left, uint right) => left & right;
    public static uint U32BitOr(uint left, uint right) => left | right;
    public static uint U32BitXor(uint left, uint right) => left ^ right;
    public static int U32Compare(uint left, uint right) => left.CompareTo(right);
    public static uint U32Div(uint left, uint right) => left / right;
    public static bool U32Eq(uint left, uint right) => left == right;
    public static bool U32Ge(uint left, uint right) => left >= right;
    public static bool U32Gt(uint left, uint right) => left > right;
    public static bool U32Le(uint left, uint right) => left <= right;
    public static bool U32Lt(uint left, uint right) => left < right;
    public static uint U32Mod(uint left, uint right) => left % right;
    public static uint U32Mul(uint left, uint right) => left * right;
    public static bool U32Ne(uint left, uint right) => left != right;
    public static uint U32Shl(uint left, int right) => left << right;
    public static uint U32Shr(uint left, int right) => left >> right;
    public static uint U32Sub(uint left, uint right) => left - right;
}

public sealed class MoonBitArray<T>
{
    public T[] Buffer;
    public int Length;
    public int Count => Length;

    public MoonBitArray()
    {
        Buffer = [];
        Length = 0;
    }

    public MoonBitArray(int capacity)
    {
        Buffer = new T[capacity];
        Length = 0;
    }

    public MoonBitArray(ReadOnlySpan<T> items)
    {
        Buffer = items.ToArray();
        Length = Buffer.Length;
    }

    public MoonBitArray(T[] buffer)
    {
        Buffer = buffer;
        Length = buffer.Length;
    }

    public MoonBitArray(T[] buffer, int length)
    {
        Buffer = buffer;
        Length = length;
    }

    public T this[int index] { get => MoonBitArray.At(this, index); set => MoonBitArray.Set(this, index, value); }

    public ReadOnlySpan<T> AsSpan() => Buffer.AsSpan(0, Length);

    public static MoonBitArray<T> MakeUninit(int length) => new(new T[length], length);

    public static MoonBitArray<T> operator +(MoonBitArray<T> left, MoonBitArray<T> right) =>
        MoonBitArray.Concat(left, right);

    public static MoonBitArray<T> operator +(MoonBitArray<T> left, MoonBitArrayView<T> right) =>
        MoonBitArray.Concat(left, right);

    public static MoonBitArray<T> operator +(MoonBitArray<T> left, MoonBitIter<T> right) =>
        MoonBitArray.Concat(left, right);

}

public static class MoonBitArray
{
    public static MoonBitArray<T> FromSpan<T>(ReadOnlySpan<T> items) => new(items);
    public static MoonBitArray<T> FromArray<T>(T[] items) => new(items.AsSpan());
    public static bool IsEmpty<T>(MoonBitArray<T> array) => array.Length == 0;

    public static MoonBitArray<T> Concat<T>(MoonBitArray<T> left, MoonBitArray<T> right)
    {
        var result = new MoonBitArray<T>(new T[left.Length + right.Length], left.Length + right.Length);
        left.AsSpan().CopyTo(result.Buffer);
        right.AsSpan().CopyTo(result.Buffer.AsSpan(left.Length));
        return result;
    }

    public static MoonBitArray<T> Concat<T>(MoonBitArray<T> left, MoonBitArrayView<T> right)
    {
        var result = new MoonBitArray<T>(new T[left.Length + right.Length], left.Length + right.Length);
        left.AsSpan().CopyTo(result.Buffer);
        right.AsSpan().CopyTo(result.Buffer.AsSpan(left.Length));
        return result;
    }

    public static MoonBitArray<T> Concat<T>(MoonBitArray<T> left, MoonBitIter<T> right) =>
        Concat(left, right.ToArray());

    public static T At<T>(MoonBitArray<T> array, int index)
    {
        var len = array.Length;
        if (index < 0 || index >= len)
        {
            throw new MoonBitPanic("panic");
        }

        return array.Buffer[index];
    }

    public static T UnsafeGet<T>(MoonBitArray<T> array, int index) => array.Buffer[index];

    public static MoonBitOption<T> Get<T>(MoonBitArray<T> array, int index)
    {
        var len = array.Length;
        return index >= 0 && index < len ? MoonBitOption<T>.Some(array.Buffer[index]) : MoonBitOption<T>.None();
    }

    public static MoonBitUnit Set<T>(MoonBitArray<T> array, int index, T value)
    {
        var len = array.Length;
        if (index < 0 || index >= len)
        {
            throw new MoonBitPanic("panic");
        }

        array.Buffer[index] = value;
        return MoonBitUnit.Value;
    }

    public static MoonBitUnit UnsafeSet<T>(MoonBitArray<T> array, int index, T value)
    {
        array.Buffer[index] = value;
        return MoonBitUnit.Value;
    }

    public static MoonBitUnit Push<T>(MoonBitArray<T> array, T item)
    {
        EnsureCapacity(array, array.Length + 1);
        array.Buffer[array.Length] = item;
        array.Length += 1;
        return MoonBitUnit.Value;
    }

    public static MoonBitOption<T> Pop<T>(MoonBitArray<T> array)
    {
        if (array.Length == 0)
        {
            return MoonBitOption<T>.None();
        }

        var index = array.Length - 1;
        var item = array.Buffer[index];
        array.Buffer[index] = default!;
        array.Length = index;
        return MoonBitOption<T>.Some(item);
    }

    public static MoonBitArray<T> Copy<T>(MoonBitArray<T> array)
    {
        var copy = new T[array.Length];
        System.Array.Copy(array.Buffer, copy, array.Length);
        return new MoonBitArray<T>(copy, array.Length);
    }

    public static MoonBitUnit ReserveCapacity<T>(MoonBitArray<T> array, int capacity)
    {
        EnsureCapacity(array, capacity);
        return MoonBitUnit.Value;
    }

    public static MoonBitUnit ShrinkToFit<T>(MoonBitArray<T> array)
    {
        if (array.Buffer.Length != array.Length)
        {
            System.Array.Resize(ref array.Buffer, array.Length);
        }

        return MoonBitUnit.Value;
    }

    public static MoonBitUnit UnsafeTruncateToLength<T>(MoonBitArray<T> array, int length)
    {
        if (length < array.Length)
        {
            System.Array.Clear(array.Buffer, length, array.Length - length);
        }

        array.Length = length;
        return MoonBitUnit.Value;
    }

    public static string JoinStrings(MoonBitArray<string> array, string separator)
    {
        if (array.Length == 0)
        {
            return "";
        }

        var builder = new System.Text.StringBuilder(array.Buffer[0]);
        for (var i = 1; i < array.Length; i++)
        {
            builder.Append(separator);
            builder.Append(array.Buffer[i]);
        }

        return builder.ToString();
    }

    private static void EnsureCapacity<T>(MoonBitArray<T> array, int capacity)
    {
        if (array.Buffer.Length >= capacity)
        {
            return;
        }

        var next = array.Buffer.Length == 0 ? 8 : array.Buffer.Length * 2;
        while (next < capacity)
        {
            next *= 2;
        }

        System.Array.Resize(ref array.Buffer, next);
    }
}

public static class MoonBitIterArrayExtensions
{
    public static MoonBitArray<T> ToArray<T>(this MoonBitIter<T> iter)
    {
        var result = new MoonBitArray<T>();
        while (true)
        {
            var item = iter.Next();
            if (item.IsNone)
            {
                return result;
            }

            MoonBitArray.Push(result, item.Value);
        }
    }
}

public static class MoonBitArrayViewBounds
{
    public static int CheckedOffset(int startOffset, int length, int index)
    {
        if ((uint)index >= (uint)length)
        {
            throw new MoonBitPanic("index out of bounds");
        }

        return startOffset + index;
    }

    public static (int Start, int Length) ValidateRange(int length, int start, int? end)
    {
        if (start < 0)
        {
            start = length + start;
        }

        var actualEnd = end ?? length;
        if (actualEnd < 0)
        {
            actualEnd = length + actualEnd;
        }

        if (start < 0 || actualEnd < start || actualEnd > length)
        {
            throw new MoonBitPanic("View index out of bounds");
        }

        return (start, actualEnd - start);
    }

    public static void ValidateAbsoluteRange(int bufferLength, int start, int length)
    {
        if (start < 0 || length < 0 || start + length > bufferLength)
        {
            throw new MoonBitPanic("View index out of bounds");
        }
    }
}

public readonly struct MoonBitArrayView<T>
{
    public T[] Buffer { get; }
    public int StartOffset { get; }

    public MoonBitArrayView(MoonBitArray<T> array, int start = 0, int? end = null)
    {
        Buffer = array.Buffer;
        (StartOffset, Length) = MoonBitArrayViewBounds.ValidateRange(array.Length, start, end);
    }

    public MoonBitArrayView(T[] array, int start = 0, int? end = null)
    {
        Buffer = array;
        (StartOffset, Length) = MoonBitArrayViewBounds.ValidateRange(array.Length, start, end);
    }

    private MoonBitArrayView(T[] buffer, int start, int length, bool _)
    {
        Buffer = buffer;
        StartOffset = start;
        Length = length;
    }

    public int Length { get; }

    public ReadOnlySpan<T> AsSpan() => Buffer.AsSpan(StartOffset, Length);

    public T this[int index] => SourceGet(CheckedOffset(index));
    public object? GetObject(int index) => this[index];

    public static implicit operator MoonBitArrayView<T>(MoonBitArray<T> array) => new(array);
    public static implicit operator MoonBitArrayView<T>(T[] array) => new(array);
    public static implicit operator MoonBitArrayView<T>(MoonBitMutArrayView<T> view) =>
        Make(view.Buffer, view.StartOffset, view.Length);

    public static MoonBitArrayView<T> Make(T[] buffer, int start, int length)
    {
        MoonBitArrayViewBounds.ValidateAbsoluteRange(buffer.Length, start, length);
        return new MoonBitArrayView<T>(buffer, start, length, true);
    }

    private T SourceGet(int index) => Buffer[index];
    private int CheckedOffset(int index) =>
        MoonBitArrayViewBounds.CheckedOffset(StartOffset, Length, index);
}

public readonly struct MoonBitMutArrayView<T>
{
    public T[] Buffer { get; }
    public int StartOffset { get; }

    public MoonBitMutArrayView(MoonBitArray<T> array, int start = 0, int? end = null)
    {
        Buffer = array.Buffer;
        (StartOffset, Length) = MoonBitArrayViewBounds.ValidateRange(array.Length, start, end);
    }

    public MoonBitMutArrayView(T[] array, int start = 0, int? end = null)
    {
        Buffer = array;
        (StartOffset, Length) = MoonBitArrayViewBounds.ValidateRange(array.Length, start, end);
    }

    private MoonBitMutArrayView(T[] buffer, int start, int length, bool _)
    {
        Buffer = buffer;
        StartOffset = start;
        Length = length;
    }

    public int Length { get; }

    public Span<T> AsSpan() => Buffer.AsSpan(StartOffset, Length);

    public T this[int index] { get => SourceGet(CheckedOffset(index)); set => SourceSet(CheckedOffset(index), value); }

    public object? GetObject(int index) => this[index];

    public static implicit operator MoonBitMutArrayView<T>(MoonBitArray<T> array) => new(array);
    public static implicit operator MoonBitMutArrayView<T>(T[] array) => new(array);

    public static MoonBitMutArrayView<T> Make(T[] buffer, int start, int length)
    {
        MoonBitArrayViewBounds.ValidateAbsoluteRange(buffer.Length, start, length);
        return new MoonBitMutArrayView<T>(buffer, start, length, true);
    }

    private T SourceGet(int index) => Buffer[index];
    private void SourceSet(int index, T value) => Buffer[index] = value;

    private int CheckedOffset(int index) =>
        MoonBitArrayViewBounds.CheckedOffset(StartOffset, Length, index);
}

public readonly struct MoonBitBytesView
{
    public MoonBitBytesView(byte[] buffer, int start, int length)
    {
        if (start < 0 || length < 0 || start + length > buffer.Length)
        {
            throw new MoonBitPanic("View index out of bounds");
        }

        Buffer = buffer;
        StartOffset = start;
        Length = length;
    }

    public byte[] Buffer { get; }
    public int StartOffset { get; }
    public int Length { get; }
    public ReadOnlySpan<byte> Span => Buffer.AsSpan(StartOffset, Length);
    public byte this[int index] => Buffer[CheckedOffset(index)];

    private int CheckedOffset(int index)
    {
        if ((uint)index >= (uint)Length)
        {
            throw new MoonBitPanic($"index out of bounds: the len is from 0 to {Length} but the index is {index}");
        }

        return StartOffset + index;
    }
}

public static class MoonBitFixedArray
{
    public static T[] Make<T>(int length, T value)
    {
        var items = new T[length];
        System.Array.Fill(items, value);
        return items;
    }

    public static MoonBitUnit Set<T>(T[] items, int index, T value)
    {
        items[index] = value;
        return MoonBitUnit.Value;
    }

    public static MoonBitUnit Set<T>(MoonBitOption<T>[] items, int index, T value)
    {
        items[index] = MoonBitOption<T>.Some(value);
        return MoonBitUnit.Value;
    }
}

public static class MoonBitBitString
{
    public static ulong ExtractUnsigned(ReadOnlySpan<byte> data, int bitOffset, int width, bool littleEndian)
    {
        if ((uint)width > 64U || width == 0)
        {
            throw new MoonBitPanic("invalid bitstring width");
        }

        if (littleEndian)
        {
            if ((width & 7) != 0)
            {
                throw new MoonBitPanic("little-endian bitstring width must be byte-aligned");
            }

            ulong value = 0;
            for (var i = 0; i < width / 8; i++)
            {
                value |= (ulong)data[(bitOffset / 8) + i] << (i * 8);
            }

            return value;
        }

        ulong result = 0;
        for (var i = 0; i < width; i++)
        {
            var absolute = bitOffset + i;
            var b = data[absolute / 8];
            var bit = (b >> (7 - (absolute & 7))) & 1;
            result = (result << 1) | (uint)bit;
        }

        return result;
    }

    public static long ExtractSigned(ReadOnlySpan<byte> data, int bitOffset, int width, bool littleEndian)
    {
        var unsigned = ExtractUnsigned(data, bitOffset, width, littleEndian);
        var signBit = 1UL << (width - 1);
        if ((unsigned & signBit) == 0)
        {
            return (long)unsigned;
        }

        return width == 64
            ? unchecked((long)unsigned)
            : (long)(unsigned - (1UL << width));
    }
}

public sealed class MoonBitStringBuilder
{
    private readonly System.Text.StringBuilder _builder;
    public MoonBitStringBuilder(int sizeHint = 0)
    {
        _builder = sizeHint > 0 ? new System.Text.StringBuilder(sizeHint) : new System.Text.StringBuilder();
    }

    public static implicit operator Logger(MoonBitStringBuilder builder) =>
        new(builder, MoonBitStringBuilderAsLogger.Instance);

    public MoonBitUnit WriteString(string value)
    {
        _builder.Append(value);
        return MoonBitUnit.Value;
    }

    public MoonBitUnit WriteString(MoonBitStringView value)
    {
        _builder.Append(value.AsSpan());
        return MoonBitUnit.Value;
    }

    public MoonBitUnit WriteChar(int value)
    {
        if(value < 0xFFFF)
        {
            _builder.Append((char)value);
        }
        else
        {
            var rune = new System.Text.Rune(value);
            Span<char> buffer = stackalloc char[4];
            var length = rune.EncodeToUtf16(buffer);
            _builder.Append(buffer.Slice(0, length));
        }
        return MoonBitUnit.Value;
    }

    public MoonBitUnit WriteSubstring(string value, int start, int length)
    {
        _builder.Append(value, start, length);
        return MoonBitUnit.Value;
    }

    public MoonBitUnit Reset()
    {
        _builder.Clear();
        return MoonBitUnit.Value;
    }

    public override string ToString() => _builder.ToString();
}

public static class MoonBitStringExtensions
{
    public static MoonBitStringView View(this string value) => new(value, 0, value.Length);
    public static MoonBitStringView View(this string value, int start) => value.View(start, value.Length);
    public static MoonBitStringView View(this string value, int start, int end)
    {
        if (start < 0)
        {
            start = value.Length + start;
        }

        if (end < 0)
        {
            end = value.Length + end;
        }

        return new(value, start, end);
    }

    public static bool ContainsOrdinal(this string value, string part) => value.Contains(part, StringComparison.Ordinal);
    public static bool HasPrefix(this string value, string prefix) => value.StartsWith(prefix, StringComparison.Ordinal);
    public static bool HasSuffix(this string value, string suffix) => value.EndsWith(suffix, StringComparison.Ordinal);
    public static bool IsEmpty(this string value) => value.Length == 0;
    public static string ReplaceAll(this string value, string oldValue, string newValue) => value.Replace(oldValue, newValue, StringComparison.Ordinal);
    public static MoonBitStringView TrimMoonBit(this string value) => value.View().Trim();
    public static string ToLowerMoonBit(this string value) => value.ToLowerInvariant();
    public static MoonBitOption<MoonBitStringView> BeforeMoonBit(this string value, string marker) => value.View().Before(marker);
    public static MoonBitOption<MoonBitStringView> AfterMoonBit(this string value, string marker) => value.View().After(marker);
    public static MoonBitOption<(MoonBitStringView, MoonBitStringView)> SplitOnceMoonBit(this string value, string marker) => value.View().SplitOnce(marker);
    public static MoonBitIter<MoonBitStringView> SplitMoonBit(this string value, MoonBitStringView separator) => value.View().Split(separator);
}

public readonly record struct MoonBitStringView(string Data, int Start, int End)
{
    public static implicit operator MoonBitStringView(string value) => new(value, 0, value.Length);
    public int Length => End - Start;
    public int StartOffset => Start;
    public string Source => Data;
    public ReadOnlySpan<char> AsSpan() => Data.AsSpan(Start, Length);

    public ushort this[int index] => (ushort)Data[Start + index];
    public MoonBitStringView Sub(int startOffset, int? endOffset = null)
    {
        var end = endOffset ?? Length;
        if (startOffset < 0)
        {
            startOffset = Length + startOffset;
        }

        if (end < 0)
        {
            end = Length + end;
        }

        if (startOffset < 0 || startOffset > end || end > Length)
        {
            throw new ArgumentOutOfRangeException(nameof(startOffset), "Invalid index for View");
        }

        return new MoonBitStringView(Data, Start + startOffset, Start + end);
    }

    public string ToOwned() => ToString();
    public override string ToString() => Data.Substring(Start, Length);
    public static bool operator ==(MoonBitStringView left, string right) => right is not null && left.AsSpan().SequenceEqual(right.AsSpan());
    public static bool operator !=(MoonBitStringView left, string right) => !(left == right);
    public static bool operator ==(string left, MoonBitStringView right) => left is not null && left.AsSpan().SequenceEqual(right.AsSpan());
    public static bool operator !=(string left, MoonBitStringView right) => !(left == right);
    public bool ContainsOrdinal(string part) => AsSpan().Contains(part.AsSpan(), StringComparison.Ordinal);
    public bool HasPrefix(string prefix) => AsSpan().StartsWith(prefix.AsSpan(), StringComparison.Ordinal);
    public bool HasSuffix(string suffix) => AsSpan().EndsWith(suffix.AsSpan(), StringComparison.Ordinal);
    public MoonBitStringView Trim()
    {
        var start = Start;
        var end = End;
        while (start < end && char.IsWhiteSpace(Data[start]))
        {
            start++;
        }

        while (end > start && char.IsWhiteSpace(Data[end - 1]))
        {
            end--;
        }

        return new MoonBitStringView(Data, start, end);
    }

    public MoonBitOption<MoonBitStringView> Before(string marker)
    {
        var index = Data.IndexOf(marker, Start, Length, StringComparison.Ordinal);
        return index < 0 ? MoonBitOption<MoonBitStringView>.None() : MoonBitOption<MoonBitStringView>.Some(new MoonBitStringView(Data, Start, index));
    }

    public MoonBitOption<MoonBitStringView> After(string marker)
    {
        var index = Data.IndexOf(marker, Start, Length, StringComparison.Ordinal);
        return index < 0 ? MoonBitOption<MoonBitStringView>.None() : MoonBitOption<MoonBitStringView>.Some(new MoonBitStringView(Data, index + marker.Length, End));
    }

    public MoonBitOption<(MoonBitStringView, MoonBitStringView)> SplitOnce(string marker)
    {
        var index = Data.IndexOf(marker, Start, Length, StringComparison.Ordinal);
        return index < 0 ? MoonBitOption<(MoonBitStringView, MoonBitStringView)>.None() : MoonBitOption<(MoonBitStringView, MoonBitStringView)>.Some((new MoonBitStringView(Data, Start, index), new MoonBitStringView(Data, index + marker.Length, End)));
    }

    public MoonBitIter<MoonBitStringView> Split(MoonBitStringView separator)
    {
        var source = this;
        var remaining = source;
        var index = 0;
        if (separator.Length == 0)
        {
            return new MoonBitIter<MoonBitStringView>(() =>
            {
                if (index >= source.Length)
                {
                    return MoonBitOption<MoonBitStringView>.None();
                }

                var item = source.Sub(index, index + 1);
                index += 1;
                return MoonBitOption<MoonBitStringView>.Some(item);
            });
        }

        return new MoonBitIter<MoonBitStringView>(() =>
        {
            if (remaining.Start > remaining.End)
            {
                return MoonBitOption<MoonBitStringView>.None();
            }

            var found = remaining.AsSpan().IndexOf(separator.AsSpan(), StringComparison.Ordinal);
            if (found < 0)
            {
                var last = remaining;
                remaining = new MoonBitStringView(source.Data, source.End + 1, source.End);
                return MoonBitOption<MoonBitStringView>.Some(last);
            }

            var item = remaining.Sub(0, found);
            remaining = remaining.Sub(found + separator.Length);
            return MoonBitOption<MoonBitStringView>.Some(item);
        });
    }
}

